[project]
name = "hello-fact-triples"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "graphiti-core[google-genai]>=0.18.2",
    "python-dotenv>=1.1.1",
]
